apiVersion: v2
name: wordpress
version: 0.14.4
appVersion: 6.8.3-apache
description: A Helm chart for Wordpress on Kubernetes
type: application

maintainers:
  - name: eyesoncloud

dependencies:
  - name: mariadb
    version: 0.3.14
    repository: https://eyesoncloud.github.io/helm-charts 
    condition: mariadb.enabled

