# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    app: nginx
    environment: {{ .Values.env }}
spec:
  type: {{ index .Values.nginx .Values.env "serviceType" }}
  selector:
    app: nginx
  ports:
    - port: {{ index .Values.nginx .Values.env "servicePort" }}
      targetPort: 80
      nodePort: {{ index .Values.nginx .Values.env "nodePort" }}


